common/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    # 비밀번호 초기화
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

community/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'community'

urlpatterns = [
    path('list/<str:category>/', views.post_list, name='list'), # sorae.gg/community/ (list)
    path('detail/<int:post_id>/', views.post_detail, name='detail'), # sorae.gg/community/post_id
    path('editor/', views.post_editor, name='editor'), # sorae.gg/community/editor
    path('<int:post_id>/editor/', views.post_modify, name='modify'),
    path('<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('<int:post_id>/vote/', views.post_vote, name='post_vote'),
    path('comment/<int:post_id>/editor/', views.comment_create, name='comment_create'),
    path('comment/<int:post_id>/delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('comment/<int:post_id>/vote/<int:comment_id>', views.comment_vote, name='comment_vote'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from common import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('summoner.urls')),
    path('community/', include('community.urls')),
    path('common/', include('common.urls')),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

community/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_post')
    voter = models.ManyToManyField(User, related_name='voter_post')
    category_name = models.CharField(max_length=10)
    hits = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_comment')
    voter = models.ManyToManyField(User, related_name='voter_comment')


class PostHits(models.Model):
    ip = models.CharField(max_length=30)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

community/forms.py
from django import forms
from community.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['subject', 'content', 'category_name']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

community/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.views import generic
from django.utils import timezone
from django.db.models import Q, Count
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from tools.tool import *
from community.models import *
from community.forms import *

'''
 나중에, View name 리팩토링 해야 됨 
'''


def post_list(request, category):
    page = request.GET.get('page', '1')
    keyword = request.GET.get('keyword', '')
    target = request.GET.get('target', '')
    sort = request.GET.get('sort', '')

    # 카테고리
    post_list = Post.objects.all()

    if category != "all":
        post_list = Post.objects.filter(category_name=category)

    # 정렬
    if sort == "popular":
        post_list = post_list.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    else:
        post_list = post_list.order_by('-create_date')

    # 검색
    if keyword:
        if target == "subject":
            post_list = post_list.filter(Q(subject__icontains=keyword)).distinct()
        elif target == "content":
            post_list = post_list.filter(Q(content__icontains=keyword)).distinct()
        elif target == "user_name":
            post_list = post_list.filter(Q(author__username__icontains=keyword)).distinct()

    # 페이징 처리
    paginator = Paginator(post_list, 15)  # 페이지당 15개의 Post 출력
    pageObj = paginator.get_page(page)

    context = {'post_list': pageObj, 'page': page, 'keyword': keyword, 'sort': sort, 'category': category}
    return render(request, 'community/post_list.html', context)


def post_detail(request, post_id):
    """
    detail 내용 출력
    """
    post = get_object_or_404(Post, pk=post_id)

    # 조회수
    ip = get_client_ip(request)
    register = PostHits.objects.filter(ip=ip, post=post).count()
    if register == 0:
        h = PostHits(ip=ip, post=post)
        h.save()
        post.hits += 1
        post.save()

    context = {'post': post}
    return render(request, 'community/post_detail.html', context)


@login_required(login_url='common:login')
def post_editor(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.create_date = timezone.now()
            post.author = request.user
            post.save()
            return redirect('community:list', category=post.category_name)
    else:
        form = PostForm()
        context = {'form': form}
        return render(request, 'community/post_editor.html', context)


@login_required(login_url='common:login')
def post_modify(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('community:detail', post_id=post.id)
    else:
        form = PostForm(instance=post)

    context = {'form': form}
    return render(request, 'community/post_editor.html', context)


@login_required(login_url='common:login')
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('community:list', category=post.category_name)


@login_required(login_url='common:login')
def post_vote(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.voter.add(request.user)
    return redirect('community:detail', post_id=post.id)


@login_required(login_url='common:login')
def comment_create(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.create_date = timezone.now()
            comment.question = post
            comment.post_id = post.id
            comment.author = request.user
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('community:detail', post_id=post.id), comment.id))
    else:
        form = CommentForm()
    context = {'post': post, 'form': form}
    return render(request, 'community/post_detail.html', context)


@login_required(login_url='common:login')
def comment_delete(request, post_id ,comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('community:detail', post_id=post_id)


@login_required(login_url='common:login')
def comment_vote(request, post_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.voter.add(request.user)
    return redirect('{}#comment_{}'.format(resolve_url('community:detail', post_id=post_id), comment.id))

templates/community/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load community_filter %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'community/css/post_detail.css' %}">
{% endblock css_link %}


{% block content %}
<div class="content-wrap">
    {% include "sidebar.html" %}
    <!-- content start -->
    <div class="post-detail-wrap">
        <!-- detail header start -->
        <div class="detail-header-wrap">
            <div class="detail-header-title">
                {{ post.subject }}
            </div>
            <div class="detail-header-meta">
                <div class="header-page">
                    {{ post.category_name|post_type }}
                </div>
                <div class="header-date">
                    {{ post.create_date|elapse_date }}
                </div>
                <div class="header-user">
                    {{ post.author.username }}
                </div>
                <div class="header-info">
                    <div class="header-info-item">
                        조회 {{ post.hits }}
                    </div>
                    <div class="header-info-item">
                        댓글수 {{ post.comment_set.count }}
                    </div>
                    <div class="header-info-item">
                        추천수 {{ post.voter.count }}
                    </div>
                </div>
            </div>
            {% if request.user == post.author or user.is_superuser %}
            <div class="detail-header-control">
                <div class="control-button-delete">
                    <a href="#" data-uri="{% url 'community:post_delete' post.id %}" class="delete">
                        삭제
                    </a>
                </div>
                <div class="control-button-modify">
                    <a href="{% url 'community:modify' post.id %}">
                        수정
                    </a>
                </div>
            </div>
            {% endif %}
        </div>
        <!-- detail header end -->
        <div class="detail-content-wrap">
            <div class="detail-content">
                    {{ post.content|mark }}
            </div>
        </div>
        <div class="detail-votebox-wrap">
            <div class="detail-votebox-count">
                <span>{{ post.voter.count }}</span>
            </div>
            <div class="detail-votebox">
                <a class="votebox recommend" href="#" data-uri="{% url 'community:post_vote' post.id %}">
                    추천
                </a>
            </div>
        </div>

        <!-- comment start -->
        <div class="detail-comment-wrap">
            <div class="comment-header">
                <h2 class="comment-header-title">
                    댓글
                </h2>
                <span class="comment-header-content">
                    총 {{ post.comment_set.count }} 개
                </span>
            </div>
            <form action="{% url 'community:comment_create' post.id %}" method="post">
                {% csrf_token %}
                <!-- Error Start -->
                {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                        {% endif %}
                    {% endfor %}
                </div>
                {% endif %}
                <!-- Error End -->
                <div class="comment-editor-wrap">
                    <div class="comment-editor">
                        <textarea name="content" class="comment-editor-input" placeholder="댓글"
                              autocomplete="off" spellcheck="false" required="true" ></textarea>
                    </div>
                    <div class="comment-editor-submit">
                        <input class="comment-submit" type="submit" value="작성">
                    </div>
                </div>
            </form>
            <div id="comment-list-container">
                {% for comment in post.comment_set.all %}
                <a id="comment_{{ comment.id }}"></a>
                <div class="comment-item-container">
                    <div class="comment-item-vote">
                        <a href="#" data-uri="{% url 'community:comment_vote' post.id comment.id %}" class="recommend">
                           <img src="{% static 'community/images/vote-icon.png' %}" width="20">
                        </a>
                    </div>
                    <div class="comment-item">
                        <div class="comment-item-meta">
                            <div class="comment-item-user">
                                {{ comment.author }}
                            </div>
                            <div class="comment-item-date">
                                몇분 전
                            </div>
                            <div class="comment-item-vote-count">
                                추천 수 {{ comment.voter.count }}
                            </div>
                            {% if request.user == comment.author or user.is_superuser %}
                            <div class="comment-item-delete">
                                <a href="#" data-uri="{% url 'community:comment_delete' post.id comment.id %}"
                                class="delete">삭제</a>
                            </div>
                            {% endif %}
                        </div>
                        <div class="comment-item-content">
                            {{ comment.content }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}
<script type="text/javascript" src="{% static 'community/js/post_detail.js' %}"></script>
{% endblock %}

templates/community/post_editor.html
{% extends 'base.html' %}
{% load static %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'community/css/post_editor.css' %}">
{% endblock css_link %}

{% block content %}
<div class="content-wrap">
    <!-- editor start -->
    <form method="post" class="post-form my-3">
        {% csrf_token %}
         <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="editor">
            <div class="editor-header">
                글 쓰기
            </div>
            <div class="editor-sort">
                <label class="editor-sort-label">
                    <select name="category_name" class="form-select-sm editor-select">
                        {% if user.is_superuser %}
                        <option value="develop">
                            개발자 소식
                        </option>
                        {% endif %}
                        <option value="free">
                            자유 게시판
                        </option>
                        <option value="bug">
                            버그 및 건의
                        </option>
                    </select>
                </label>
            </div>
            <div class="editor-title">
                <label class="editor-title-label">
                    <input type="text" name="subject" class="editor-title-input" placeholder="제목"
                    autocomplete="off" required="true" value="{{ form.subject.value|default_if_none:'' }}">
                </label>
            </div>
            <div class="editor-content">
                <label class="editor-content-label">
                    <textarea type="text" name="content" class="editor-content-input" placeholder="본문"
                              autocomplete="off" spellcheck="false" required="true"
                              value="form.content.value|default_if_none:''"></textarea>
                </label>
            </div>
            <div class="editor-button">
                <div class="editor-button-item">
                    <button type="submit" class="btn btn-primary">등록</button>
                </div>
            </div>
        </div>
    </form>
    <!-- editor end -->
</div>
{% endblock content %}

templates/community/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load community_filter %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'community/css/post_list.css' %}">
{% endblock css_link %}


{% block content %}

<div class="content-wrap">
    <!-- side bar -->
    {% include "sidebar.html" %}
    <!-- content start -->
    <div class="post-list-wrap">
        <!-- post header start -->
        <div class="post-header-wrap">
            <div class="post-header">
                <div class="post-search-wrap">
                    <select name="target" class="form-select-sm post-search-select target">
                        <option value="subject">
                            제목
                        </option>
                        <option value="content">
                            내용
                        </option>
                        <option value="user_name">
                            작성자
                        </option>
                    </select>
                    <input type="text" name="keyword" class="form-control-sm post-search-input keyword" placeholder="검색"
                           value="{{ keyword|default_if_none:'' }}">
                    <button class="post-search-button" id="search_button">
                        <img src="{% static 'community/images/search-icon.png'%}" class="search-image" alt="검색">
                    </button>
                </div>
                <div class="post-editor-wrap">
                    <form action="{% url 'community:editor' %}" method="get" id="post-editor">
                        {% csrf_token %}
                        <button class="post-editor-button">
                            <img src="{% static 'community/images/pencil.png'%}" width="28" >
                        </button>
                    </form>
                </div>
            </div>
            <div class="post-sortbox-wrap">
                <div class="post-sortbox" href="#" data-sort="recent">
                    <img src="{% static 'community/images/time-icon.png' %}" width="20">
                    <span>최신순</span>
                </div>
                <div class="post-sortbox" href="#" data-sort="popular">
                    <img src="{% static 'community/images/popular-icon.png' %}" width="20">
                    <span>인기순</span>
                </div>
            </div>
        </div>
        <!-- post header end-->
        <!-- post content start -->
        {% if post_list %}
            <div class="post-list-container">
                {% for post in post_list %}
                <div class="post-item-container">
                    <div class="post-item-vote">
                        <img src="{% static 'community/images/vote-icon.png'%}" width="14" >
                        <span>{{ post.voter.count }}</span>
                    </div>
                    <div class="post-item-content">
                        <a href="{% url 'community:detail' post.id %}">
                            {{ post.subject }}
                        </a>
                        {% if post.comment_set.count > 0 %}
                            <span class="comment-count">[{{ post.comment_set.count }}]</span>
                        {% endif %}
                    </div>
                    <div class="post-item-date">
                        <span>{{ post.create_date|elapse_date }}</span>
                    </div>
                    <div class="post-item-user">
                        <span>{{ post.author.username }}</span>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
        <!-- post content end -->
        <!-- post page start -->
        <div class="post-paging">
            <ul class="pagination justify-content-center">
                <!-- previous page -->
                {% if post_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="#" data-page="{{ post_list.previous_page_number }}">◀</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">◀</a>
                </li>
                {% endif %}
                <!-- page list -->
                {% for page_number in post_list.paginator.page_range %}
                    {% if page_number >= post_list.number|add:-5 and page_number <= post_list.number|add:5 %}
                        {% if page_number == question_list.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#" data-page="{{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="#" data-page="{{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                <!-- next page -->
                {% if post_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="#" data-page="{{ post_list.next_page_number }}">▶</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">▶</a>
                </li>
                {% endif %}
            </ul>
        </div>
         <!-- post page end -->
    </div>
    <!-- content end -->
</div>
<form id="searchForm" method="get" action="{% url 'community:list' category %}">
    <input type="hidden" id="target" name="target">
    <input type="hidden" id="keyword" name="keyword" value="{{ keyword|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="sort" name="sort" value="{{ sort }}">
</form>
{% endblock content %}

{% block script %}
<script type="text/javascript" src="{% static 'community/js/post_list.js' %}"></script>
{% endblock %}