common/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    # 비밀번호 초기화
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from common import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('summoner.urls')),
    path('community/', include('community.urls')),
    path('common/', include('common.urls')),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
import django.contrib.auth.forms as auth_forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserForm(auth_forms.UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

    def clean_username(self):
        data = self.cleaned_data['username']
        if 1 < len(data) < 9:
            return data
        else:
            raise ValidationError("은 2자 이상, 8자 이하만 가능합니다.")

    def clean_email(self):
        data = self.cleaned_data['email']

        if data.split('@')[1] != 'gmail.com':
            raise ValidationError("은 Gmail 형식의 이메일만 지원합니다.")



class PasswordResetForm(auth_forms.PasswordResetForm):
    username = auth_forms.UsernameField(label="사용자 ID")
    """
    validation 절차
    1. username에 대응하는 User 인스턴스가 존재하는지 확인
    2. username에 대응하는 email과 입력받은 email이 동일한지 확인
    """
    def clean_username(self):
        data = self.cleaned_data['username']
        if not User.objects.filter(username=data).exists():
            raise ValidationError("해당 사용자가 존재하지 않습니다.")

        return data

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        email = cleaned_data.get("email")
        if username and email:
            if User.objects.get(username=username).email != email:
                raise ValidationError("입력한 이메일 주소와 사용자의 이메일 주소가 일치하지 않습니다.")

    def get_users(self, email):
        active_users = User.objects.filter(**{
            'username__iexact': self.cleaned_data["username"],
            'is_active': True,
        })
        return (
            u for u in active_users
            if u.has_usable_password()
        )

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from common.forms import *


def signup(request):
    """
    create user account
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('community:list', category='all')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


class PasswordResetView(auth_views.PasswordResetView):
    """
    reset password : input user's email
    """
    template_name = 'common/password_reset.html'
    success_url = reverse_lazy('common:password_reset_done')
    form_class = PasswordResetForm



class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    """
    reset password : sending email
    """
    template_name = 'common/password_reset_done.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    """
    reset password : input new password
    """
    template_name = 'common/password_reset_confirm.html'
    success_url = reverse_lazy('common:login')

templates/common/login.html
{% extends "base.html" %}
{% load static %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'common/css/login.css' %}">
{% endblock css_link %}

{% block content %}
<div class="login-wrap">
    <div class="login">
        <div class="login-header">
            <div class="login-header-title">
                로그인
            </div>
            <div class="login-header-signup">
                <a href="{% url 'common:signup' %}">회원가입</a>
            </div>
        </div>
        <div class="login-content">
            <form method="post" class="post-form" action="{% url 'common:login' %}">
                {% csrf_token %}
                <!-- login success, jump to URL -->
                <input type="hidden" name="next" value="{{ next }}">
                {% include "form_errors.html" %}
                <div class="form-group">
                    <label for="username">아이디</label>
                    <input type="text" class="form-control" name="username" id="username"
                           value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="password">비밀번호</label>
                    <input type="password" class="form-control" name="password" id="password"
                           value="{{ form.password.value|default_if_none:'' }}">
                </div>
                <div class="form-button-wrap">
                    <div class="form-button">
                        <button type="submit" class="btn btn-primary">로그인</button>
                    </div>
                </div>
            </form>
            <div class="forgot-password">
                <a href="{% url 'common:password_reset' %}">비밀번호를 잊으셨나요?</a>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/common/password_reset.html
{% extends "base.html" %}
{% load static %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'common/css/password_reset.css' %}">
{% endblock css_link %}

{% block content %}
<div class="password-wrap">
    <div class="password">
        <div class="password-header">
            <div class="password-header-title">
                비밀번호 분실
            </div>
        </div>
        <div class="password-content">
            <div class="description">
                비밀번호 재설정을 위해 회원가입시 등록했던 이메일 주소를 입력하세요.
            </div>
            <form method="post" class="post-form">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="form-group">
                    <label for="username">아이디</label>
                    <input type="text" class="form-control" name="username" id="username"
                           value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="email">이메일</label>
                    <input type="text" class="form-control" name="email" id="email"
                           value="{{ form.email.value|default_if_none:'' }}">
                </div>
                <div class="form-button-wrap">
                    <div class="form-button">
                        <button type="submit" class="btn btn-primary">제출</button>
                    </div>
                </div>
            </form>
            <div class="back-login">
                <a href="{% url 'common:login' %}">로그인으로 돌아가기</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/common/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'common/css/password_reset.css' %}">
{% endblock css_link %}

{% block content %}
<div class="password-wrap">
    <div class="password">
        <div class="password-header">
            <div class="password-header-title">
                비밀번호 분실
            </div>
        </div>
        <div class="password-content">
            {% if validlink %}
            <form method="post" class="post-form">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="form-group">
                    <label for="new_password1">새로운 비밀번호</label>
                    <input type="password" class="form-control" name="new_password1" id="new_password1">
                </div>
                <div class="form-group">
                    <label for="new_password2">새로운 비밀번호 확인</label>
                    <input type="password" class="form-control" name="new_password2" id="new_password2">
                </div>
                <div class="form-button-wrap">
                    <div class="form-button">
                        <button type="submit" class="btn btn-primary">변경하기</button>
                    </div>
                </div>
            </form>
            {% else %}
            <div>링크가 유효하지 않습니다.</div>
            {% endif %}
            <div class="back-login">
                <a href="{% url 'common:login' %}">로그인으로 돌아가기</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/common/password_reset_done.html
{% extends "base.html" %}
{% load static %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'common/css/password_reset.css' %}">
{% endblock css_link %}

{% block content %}
<div class="password-wrap">
    <div class="password">
        <div class="password-header">
            <div class="password-header-title">
                비밀번호 분실
            </div>
        </div>
        <div class="password-content">
            <div class="description-done">
                이메일 전송이 완료되었습니다.
            </div>
            <div class="back-login">
                <a href="{% url 'common:login' %}">로그인으로 돌아가기</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/common/signup.html
{% extends 'base.html' %}
{% load static %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'common/css/signup.css' %}">
{% endblock css_link %}

{% block content %}
<div class="signup-wrap">
    <div class="signup">
        <div class="signup-header">
            <div class="signup-header-title">
                회원가입
            </div>
            <div class="signup-header-login">
                <a href="{% url 'common:login' %}">로그인</a>
            </div>
        </div>
        <div class="signup-content">
            <form method="post" class="post-form" action="{% url 'common:signup' %}">
                {% csrf_token %}
                {% include "form_errors.html" %}
                    <div class="form-group">
                        <label for="username">아이디</label>
                        <input type="text" class="form-control" name="username" id="username"
                               value="{{ form.username.value|default_if_none:'' }}">
                    </div>
                    <div class="form-group">
                        <label for="password1">비밀번호</label>
                        <input type="password" class="form-control" name="password1" id="password1"
                               value="{{ form.password1.value|default_if_none:'' }}">
                    </div>
                    <div class="form-group">
                        <label for="password2">비밀번호 확인</label>
                        <input type="password" class="form-control" name="password2" id="password2"
                               value="{{ form.password2.value|default_if_none:'' }}">
                    </div>
                    <div class="form-group">
                        <label for="email">이메일</label>
                        <input type="text" class="form-control" name="email" id="email"
                               value="{{ form.email.value|default_if_none:'' }}">
                        <span class="email-description"> ※ 본인의 이메일 주소를 정확하게 입력하세요. 비밀번호 분실시 사용됩니다. </span>
                    </div>
                    <div class="form-button-wrap">
                        <div class="form-button">
                            <button type="submit" class="btn btn-primary">가입</button>
                        </div>
                    </div>
            </form>
        </div>
    </div>
</div>


{% endblock content %}