common/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    # 비밀번호 초기화
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

community/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'community'

urlpatterns = [
    path('list/<str:category>/', views.post_list, name='list'), # sorae.gg/community/ (list)
    path('detail/<int:post_id>/', views.post_detail, name='detail'), # sorae.gg/community/post_id
    path('editor/', views.post_editor, name='editor'), # sorae.gg/community/editor
    path('<int:post_id>/editor/', views.post_modify, name='modify'),
    path('<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('<int:post_id>/vote/', views.post_vote, name='post_vote'),
    path('comment/<int:post_id>/editor/', views.comment_create, name='comment_create'),
    path('comment/<int:post_id>/delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('comment/<int:post_id>/vote/<int:comment_id>', views.comment_vote, name='comment_vote'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from common import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('summoner.urls')),
    path('community/', include('community.urls')),
    path('common/', include('common.urls')),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--title-->
    <title>{% block title %}{% endblock title%}</title>
    <!--google font-->
    {% include "font.html" %}
    <!--bootstrap css-->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <!--main css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'community/css/sidebar.css' %}">
    <!--link css-->
    {% block css_link %}
    {% endblock css_link %}
    <!--font apply-->
    <style>
        body { font-family: "Roboto", "Noto Sans KR", sans-serif; }
    </style>

</head>

<body>
<!-- navigation bar-->
{% include "nav.html" %}

<!-- main content start -->
{% block content %}

{% endblock content %}
<!-- main content end -->

<!--footer-->
{% include "footer.html" %}

<!--jQuery-->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap js-->
<script src="{% static 'popper.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>



{% block script %}
<!-- link javascript-->
{% endblock script %}
<script src="https://unpkg.com/popper.js@1"></script>
<script src="https://unpkg.com/tippy.js@5/dist/tippy-bundle.iife.js"></script>
</body>
</html>

templates/font.html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100&family=Poppins:wght@200;500&display=swap" rel="stylesheet">

templates/footer.html
<!--footer-->
<div class="footer container-fluid">
    <div class="footer-content">
        <h3 autocapitalize="off">sorae.gg</h3>
        <p>You can search for summoners' informations and pvp logs of League of legneds.<br>
            Developers: 김남주, 김성민, 박민수</p>
    </div>
</div>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/nav.html
{% load static %}
<!--navbar start-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <!--logo-->
        <a class="navbar-brand" href="/">
            <!-- <img src="{% static 'images/home-logo.png' %}" alt="sorae.gg" width="120px" height="100px"> -->
            <h1 class='me-3' style="font-family: 'Poppins', sans-serif; font-weight: 200; font-size: 50px;">SORAE.GG</h1>
        </a>
        <!--logo-->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
         
            <li class="nav-item fs-2">
                <a class="nav-link active" aria-current="page" href="{% url 'community:list' 'all' %}">Community</a>
            </li>
            <!--
            <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
            </li>
         -->
        </ul>
        </div>
    </div>
</nav>
<!--navbar end-->

templates/sidebar.html
<!-- sidebar -->
<div class="sidebar">
    <div class="sidebar-content-wrap">
        <div class="sidebar-header">
            {% if user.is_authenticated %}
            <div class="profile-wrap">
                <div class="profile-img">
                    <img src="/static/community/images/user-icon.png">
                </div>
                <div class="profile-content-wrap">
                    <div class="profile-username">
                        <span>
                            {{ user.username }}
                        </span>
                    </div>
                </div>
            </div>
            {% endif %}
            <div class="sidebar-button">
                <div class="sidebar-button-item">
                    {% if user.is_authenticated %}
                        <a href="{% url 'common:logout' %}" class="button">Logout</a>
                    {% else %}
                        <a href="{% url 'common:login' %}" class="button">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="sidebar-content">
            <div class="sidebar-menu">
                <ul class="sidebar-menu-list">
                    <li class="sidebar-menu-item">
                        <a class="post-type" href="{% url 'community:list' 'all' %}">전체</a>
                    </li>
                    <li class="sidebar-menu-item">
                        <a class="post-type" href="{% url 'community:list' 'develop' %}">개발자 소식</a>
                    </li>
                    <li class="sidebar-menu-item">
                        <a class="post-type" href="{% url 'community:list' 'free' %}">자유 게시판</a>
                    </li>
                    <li class="sidebar-menu-item">
                        <a class="post-type" href="{% url 'community:list' 'bug' %}">버그 및 건의</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>