common/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    # 비밀번호 초기화
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from common import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('summoner.urls')),
    path('community/', include('community.urls')),
    path('common/', include('common.urls')),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

summoner/urls.py
from django.urls import include, path
from django.contrib import admin
from summoner.views import *

app_name = 'summoner'

urlpatterns = [
    path('', index, name='index'),  # sorae.gg/
    path('summoner/', SummonerView.as_view(), name='search'),  # sorae.gg/summoner/?userName=
    path('detail/', DetailView.as_view()), # sorae.gg/detail/?matchID=
    path('renew/', RenewView.as_view()), # sorae.gg/renew/?userName=
    path('ingame/', InGameView.as_view()), # sorae.gg/ingame/?userName=
]

summoner/models.py
from django.db import models
from unixtimestampfield.fields import UnixTimeStampField
'''
모델 변경사항 있을 시,
makemigrations & migrate 해줘야 함
'''


class User(models.Model):
    """
    유저 정보
    summoner_name 으로 조회
    """
    summoner_name = models.CharField(max_length=20, primary_key=True)
    summoner_level = models.SmallIntegerField()
    summoner_icon = models.SmallIntegerField()

    # 솔로 랭크
    solo_tier = models.CharField(max_length=20)
    solo_rank = models.CharField(max_length=20)
    solo_wins = models.SmallIntegerField()
    solo_losses = models.SmallIntegerField()
    solo_leaguePoints = models.SmallIntegerField()
    solo_progress = models.CharField(max_length=5)

    # 자유 랭크
    free_tier = models.CharField(max_length=20)
    free_rank = models.CharField(max_length=20)
    free_wins = models.SmallIntegerField()
    free_losses = models.SmallIntegerField()
    free_leaguePoints = models.SmallIntegerField()
    free_progress = models.CharField(max_length=5)


class GameRecord(models.Model):
    """
    게임 정보 대한 테이블
    summoner_name 으로 조회
    """
    game_ID = models.CharField(max_length=33, primary_key=True)  # summonerName + matchID
    match_ID = models.CharField(max_length=13)
    queue_ID = models.SmallIntegerField()                        # 420:솔로랭크, 440:자유랭크, 450:칼바람나락, 900: URF
    summoner_name = models.CharField(max_length=20)

    champ_name = models.CharField(max_length=20)
    champ_ID = models.SmallIntegerField()

    kill = models.SmallIntegerField()
    death = models.SmallIntegerField()
    assist = models.SmallIntegerField()

    game_result = models.BooleanField()
    game_duration = models.IntegerField()
    game_start = models.DateTimeField()
    game_end = models.DateTimeField()

    class Meta:
        ordering = ['-game_end']

class DetailRecord(models.Model):
    """
    한 게임 세부정보에 대한 테이블
    match_ID 으로 조회
    """
    game_ID = models.CharField(max_length=33, primary_key=True)  # summonerName + matchID
    match_ID = models.CharField(max_length=13)
    summoner_name = models.CharField(max_length=20)
    team_ID = models.SmallIntegerField()                         # (100: 블루, 200: 레드)
    game_result = models.BooleanField()

    minion_kill = models.SmallIntegerField()
    jungle_kill = models.IntegerField()

    champ_name = models.CharField(max_length=20)
    champ_ID = models.SmallIntegerField()
    champ_level = models.SmallIntegerField()
    total_damage = models.IntegerField()
    total_damage_object = models.IntegerField()
    total_damage_taken = models.IntegerField()
    total_heal = models.IntegerField()
    total_shield = models.IntegerField()
    total_CC = models.IntegerField()
    vision_score = models.SmallIntegerField()

    primary_rune = models.SmallIntegerField()
    sub_rune = models.SmallIntegerField()
    sub_rune_one = models.SmallIntegerField()
    sub_rune_two = models.SmallIntegerField()

    item0 = models.SmallIntegerField()
    item1 = models.SmallIntegerField()
    item2 = models.SmallIntegerField()
    item3 = models.SmallIntegerField()
    item4 = models.SmallIntegerField()
    item5 = models.SmallIntegerField()
    item6 = models.SmallIntegerField()

    spell1 = models.IntegerField()
    spell2 = models.IntegerField()

    kill = models.SmallIntegerField()
    death = models.SmallIntegerField()
    assist = models.SmallIntegerField()

    baron = models.SmallIntegerField()
    dragon = models.SmallIntegerField()
    turret = models.SmallIntegerField()

    gold_earned = models.IntegerField()
    gold_spent = models.IntegerField()

    

    


class Renew(models.Model):
    summoner_name = models.CharField(max_length=20, primary_key=True)
    create_time = models.DateTimeField(auto_now_add=True)
    renew_time = UnixTimeStampField(default=0)


class UpdateDB:
    """
    Implements CRUD about DB data
    - create Object
    DB = UpdateDB('userName')
    - use method
    UpdateDB module is used by passing the data obtained with SummonerData as parameter.
    ex) DB.createTier(info)
    """

    def __init__(self, summonerName):
        self._summonerName = summonerName

    def createUser(self, info):
        """
        Create record of Summoner table
        """
        _modelInstance = User(summoner_name=info['user']['name'], summoner_level=info['user']['summonerLevel'],
                              summoner_icon=info['user']['summonerIcon'],
                              solo_tier=info['solo']['tier'], solo_rank=info['solo']['rank'],
                              solo_wins=info['solo']['wins'], solo_losses=info['solo']['losses'],
                              solo_leaguePoints=info['solo']['leaguePoints'],
                              solo_progress=info['solo']['progress'],
                              free_tier=info['free']['tier'], free_rank=info['free']['rank'],
                              free_wins=info['free']['wins'], free_losses=info['free']['losses'],
                              free_leaguePoints=info['free']['leaguePoints'],
                              free_progress=info['free']['progress'])

        _modelInstance.save()

    def createGameRecord(self, info):
        """
        Create record of GameRecord table
        """
        _modelInstance = GameRecord(game_ID=info['summonerName'] + info['matchID'],
                                    match_ID=info['matchID'], queue_ID=info['queueID'],
                                    summoner_name=self._summonerName,
                                    champ_name=info['champName'], champ_ID=info['champID'],
                                    kill=info['kill'], death=info['death'], assist=info['assist'],
                                    game_result=info['gameResult'], game_duration=info['gameDuration'],
                                    game_start=info['gameStartTime'], game_end=info['gameEndTime'])
        _modelInstance.save()

    def createDetailRecord(self, info):
        """
        Create record of DetailRecord table
        """
        _modelInstance = DetailRecord(game_ID=info['summonerName'] + info['matchID'],
                                      match_ID=info['matchID'], team_ID=info['teamID'],
                                      game_result=info['gameResult'], summoner_name=info['summonerName'],
                                      minion_kill=info['minionKill'], jungle_kill=info['jungleKill'],
                                      champ_name=info['champName'], champ_ID=info['champID'],
                                      champ_level=info['champLevel'],
                                      total_damage=info['totalDamage'], vision_score=info['visionScore'],
                                      primary_rune=info['runes'][0], sub_rune=info['runes'][1],
                                      sub_rune_one=info['runes'][2], sub_rune_two=info['runes'][3],
                                      item0=info['items'][0], item1=info['items'][1], item2=info['items'][2],
                                      item3=info['items'][3], item4=info['items'][4], item5=info['items'][5],
                                      item6=info['items'][6],
                                      spell1=info['spells'][0], spell2=info['spells'][1],
                                      kill=info['kill'], death=info['death'], assist=info['assist'],
                                      baron=info['baron'], dragon=info['dragon'], turret=info['turret'], 
                                      total_damage_object=info['totalObjectDamage'], total_damage_taken=info['totalDamageTaken'],
                                      total_heal=info['totalHeals'], total_shield=info['totalShield'],
                                      total_CC=info['totalCC'], gold_earned=info['goldEarned'],
                                      gold_spent=info['goldSpent'])
        _modelInstance.save()

    def createRenew(self, info):
        """
        Create record of Renew table
        """
        _modelInstance = Renew(summoner_name=info)
        _modelInstance.save()

    def deleteGameRecord(self, summonerName):
        """
        Delete all record of GameRecord table
        """
        _modelInstance = GameRecord.objects.all()
        _modelInstance = _modelInstance.filter(summoner_name=summonerName)
        _modelInstance.delete()

    def deleteDetailRecord(self, matchID):
        """
        Delete all record of DetailRecord table
        """
        _modelInstance = DetailRecord.objects.all()
        _modelInstance = _modelInstance.filter(match_ID=matchID)
        _modelInstance.delete()

if __name__ == "__main__":
    DB = UpdateDB("민스님")
    DB.saveTier()

summoner/views.py
from urllib import response
import django
import json
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .serializers import UserSerializer, GameRecordSerializer, DetailRecordSerializer
from summoner.models import GameRecord, User, DetailRecord, Renew, UpdateDB
from riotapi.SummonerData import SummonerAPI
from django.core.exceptions import ObjectDoesNotExist
from config.settings import STATIC_URL
from datetime import datetime
from django.views import View
from django.template import loader
import time


def index(request):
    return render(request, 'summoner/index.html')


class SummonerView(View):

    def get(self, request):

        # URL : sorae.gg/summoner?userName
        inputName = request.GET['userName']
        summoner = SummonerAPI(inputName)
        summonerName = summoner.getName()

        # 소환사 이름이 없을때
        if summonerName == None:
            return render(request, 'summoner/summoner_info.html', {'userName': inputName})

        # DB 조회
        # alternative : get_object_or_404(User, summoner_name=summonerNmae)
        try:
            userQuery = User.objects.get(summoner_name=summonerName)
            # gameRecordData = summoner.getTotalRecord(0, 20)
        except ObjectDoesNotExist:
            """
            if Data dosen't exist then create DB
            """
            # Data 생성 및 저장
            tierData = summoner.getTier()
            gameRecordData = summoner.getTotalRecord(0, 20)
            renewData = summoner.getRenew()
            userQuery = User.objects.get(summoner_name=summonerName)

        # serializer
        recordQuery = GameRecord.objects.filter(summoner_name=summonerName)[:20]  # 20 게임 불러오기
        userSerialize = UserSerializer(userQuery)
        gameRecordSerialize = GameRecordSerializer(recordQuery, many=True)

        return render(request, 'summoner/summoner_info.html',
                      {'user': userSerialize.data, 'record': gameRecordSerialize.data
                          , 'STATIC_URL': STATIC_URL})

    def post(self, request):
        '''
        renew summoner's info
        '''
        try:
            summonerName = json.loads(request.body).get('userName')
            summoner = SummonerAPI(summonerName)
            summonerName = summoner.getName()

            if summonerName == None:
                return JsonResponse({'status': 400})

            curTime = int(time.mktime(datetime.now().timetuple()))
            try:            
                lastRecordQuery = GameRecord.objects.filter(summoner_name=summonerName)[0]
                lastMatchTime = int(time.mktime(lastRecordQuery.game_end.timetuple()))

                # Data 갱신
                tierData = summoner.getTier()
                gameRecordData = summoner.getRecordUsingTime(lastMatchTime, curTime)
            except GameRecord.DoesNotExist:
                tierData = summoner.getTier()
                gameRecordData = summoner.getRecord(0, 20)

            # 전적 시간 갱신
            renewQuery = Renew.objects.get(summoner_name=summonerName)
            renewQuery.renew_time = time.mktime(datetime.today().timetuple())
            renewQuery.save()

            return JsonResponse({'status': 200})

        except Exception:
            return JsonResponse({'status': 400})


class DetailView(View):

    def get(self, request):

        matchID = request.GET['matchID']

        # serializer
        try:
            detailQuery = DetailRecord.objects.filter(match_ID=matchID)
            detailRecordSerialize = DetailRecordSerializer(detailQuery, many=True)
            data = detailRecordSerialize.data
            blue_team = data[:5]
            red_team = data[5:]
            res = loader.render_to_string('summoner/record_detail.html', {'blue': blue_team, 'red': red_team})
            # return render(None, 'summoner/record_detail.html', {'blue':blue_team, 'red':red_team})
            return JsonResponse({'data': res})

        except ObjectDoesNotExist:
            return JsonResponse({'message': "Match ID Not Found"}, status=404)


class RenewView(View):

    def get(self, request):
        inputName = request.GET['userName']

        # API
        summoner = SummonerAPI(inputName)
        summonerName = summoner.getName()

        # DB 조회
        try:
            renewQuery = Renew.objects.get(summoner_name=summonerName)
            return JsonResponse(int(renewQuery.renew_time), status=200, safe=False)
        except ObjectDoesNotExist:
            return JsonResponse({'message': "Summoner Not Found"}, status=404)


class InGameView(View):

    def get(self, request):
        inputName = request.GET['userName']

        # API
        summoner = SummonerAPI(inputName)

        try:
            '''
            Detail View 형식으로 변경 ?
            '''
            inGameData = summoner.getInGame()
            return JsonResponse(inGameData, status=200, safe=False)
        except KeyError:
            return JsonResponse({'message': "Data Not Found"}, status=404)

templates/summoner/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Test 전적검색{% endblock title %}
    <!--font-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">



{% block content %}

<div class="l-container container-fluid">

    <div class="logo">
        <img src="{% static 'images/league-of-legends-black.png' %}" title = "" alt = "" class = "logo-image">
    </div>

    <div class="serach-box">
        <form class="search-form" action = "{% url 'summoner:search' %}" method="get" autocomplete="off">
            <!-- <input type="text" name="userName" class="search-text" placeholder="소환사명을 입력해주세요" autocomplete="off"> -->
            <div class="input-group mb-3 search-text">
                <span class="input-group-text" id="inputGroup-sizing-default">소환사명</span>
                <input type="text" required="required" name="userName" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" autocomplete="off" placeholder="소환사명을 입력해주세요">
                <button type="submit" class="btn btn-outline-secondary btn-sm">
                    <img src="{% static 'images/search-icon.png' %}" class="search-icon">
                </button>
            </div>
        </form>
    </div>
</div>
<!--empty-->
<div class="empty"></div>

{% endblock content %}

templates/summoner/summoner_info.html
{% extends 'base.html' %}
{% load summoner_filter %}
{% load static %}

{% block title %}
{% if user.summoner_name %}
 소환사 : {{ user.summoner_name }}
{% else %}
 소환사 정보 없음
{% endif %} 
{% endblock title %}

{% block css_link %}
<!-- Link Swiper's CSS -->
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css"/>

<link rel="stylesheet" href="{% static 'css/summoner.css' %}">
<link rel="stylesheet" href="{% static 'css/card.css' %}">
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
<link rel="stylesheet" href="{% static 'css/view.css' %}">
{% endblock css_link %}


{%block content%}
<div class="container-fluid">

    <!-- search box -->
    <div class="serach-box">
        {% if user.summoner_name %}
        <button type="button" class="renewBtn btn btn-primary">
            <span class ="renewText">프로필 갱신</span>
            <div class="spinner-border" style="display: none;" role="status">
                <span class="visually-hidden">Loading...</span>
              </div>
        </button>
        {% endif %}
        <form class="search-form" action = "{% url 'summoner:search' %}" method="get" autocomplete="off">
            <div class="input-group input-group-sm mb-3 summoner-search-box">
                <span class="input-group-text" id="inputGroup-sizing-default">소환사명</span>
                <input type="text" required="required" name="userName" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" autocomplete="off">
                <button type="submit" class="btn btn-outline-secondary btn-sm">
                    <img src="{% static 'images/search-icon.png' %}" class="search-icon">
                </button>
            </div>
        </form>
    </div>
    <!-- search box end -->

{% if user.summoner_name %} <!-- 소환사 정보가 존재하면 -->

    <!--소환사 정보 Start-->

    <!-- 레벨 및 아이콘-->
    <div class="summoner-info mt-4">
        <p class="text-center">
            <span class="summonerName fs-1">{{ user.summoner_name }}</span>
        </p>
        <div class="icon-frame mt-3 text-center">
            <!--summoner icon-->
            <img class="summonerIcon rounded-circle" src="http://ddragon.leagueoflegends.com/cdn/12.2.1/img/profileicon/{{user.summoner_icon}}.png">
        </div>
        
        <p class="summonerLevel bg-dark rounded-pill text-center py-1" style="color: white;">{{user.summoner_level}}</p>
    </div>

    <!-- solo-rank info / free-rank info -->
    <!--solo rank-->
    <div class="rank-info my-5">
        <div class="rank-wrap">
            <div class="rank-box solo-rank">
                {% if user.solo_tier|length > 0 %} <!--if summoner is ranked-->
                <p class="text-center my-2 fs-5">솔로랭크</p>
                <p class="text-center my-2 fs-3 tier-name">
                    <span class="soloRank">{{ user.solo_tier }}</span>
                    <span class="soloTier"> {{ user.solo_rank }}</span><br>
                    <span class="soloPoint" style ="font-size: 15px;"> {{user.solo_leaguePoints}} LP</span><br>
                    <span class="soloProgress" style ="font-size: 20px;">{{user.solo_progress|cur_progress}}</span>
                </p>
                <!--image-->
                <div class="tierImgDiv my-2 text-center">
                    <img class="tierImg soloImg" src="" alt="">
                </div>
                <div class="WinLose">
                    <span class="soloWin">{{ user.solo_wins }}승</span>
                    <span class="soloLose">{{ user.solo_losses}}패</span>
                    <span class="soloWinRatio">/ </span>
                </div>
                {% else %} <!--if summoner is unranked-->
                <p class="text-center my-2 fs-5">솔로랭크</p>
                <p class="text-center my-3 fs-3 tier-name">
                    <span>Unranked</span>
                </p>
                <div class="tierImgDiv text-center">
                    <img class="tierImg soloImg" src="{% static 'images/ranked-emblems/Unranked.png' %}" alt="unranked">
                </div>
                
                {% endif %}
            </div>
            <!--free rank-->
            <div class="rank-box free-rank">
                {% if user.free_tier|length > 0 %} <!-- if summoner is ranked -->
                <p class="text-center my-2 fs-5">자유 5:5 랭크</p>
                <p class="text-center my-2 fs-3 tier-name">
                    <span class="freeRank">{{ user.free_tier }}</span>
                    <span class="freeTier"> {{ user.free_rank }}</span><br>
                    <span class="freePoint" style="font-size: 15px;"> {{user.free_leaguePoints}} LP</span>
                    <span class="freeProgress" style ="font-size: 20px;">{{user.free_progress|cur_progress}}</span>
                </p>
                <!--image-->
                <div class="tierImgDiv my-2 text-center">
                    <img class="tierImg freeImg" src="" alt="">
                </div>
                <div class="WinLose">
                    <span class="freeWin">{{ user.free_wins }}승</span>
                    <span class="freeLose">{{ user.free_losses}}패</span>
                    <span class="freeWinRatio">/ </span>
                </div>
                {% else %} <!--if summoner is unranked-->
                <p class="text-center my-2 fs-5">자유 5:5 랭크</p>
                <p class="text-center my-3 fs-3 tier-name">
                    <span>Unranked</span>
                </p>
                <div class="tierImgDiv text-center">
                    <img class="tierImg freeImg" src="{% static 'images/ranked-emblems/Unranked.png' %}" alt="unranked">
                </div>

                {% endif %}
            </div>
        </div>
    </div>
    <!-- rank-info end -->

    <!-- game record card start -->
    <div class="record">

        <section class="record-section">

            <div class="record-container swiper mySwiper">
                <div class="record-content swiper-wrapper">
                    
                    {% for r in record %}
                    <div class="card swiper-slide" data-match-id={{r.match_ID}} data-match-time={{r.game_duration}} data-result={{r.game_result}}>
                        <div class="card-content">
                            <div class="champion-img">
                                <img src="" alt={{r.champ_name}}>
                            </div>
                            <div class="champion-name">
                                <span class="name">{{r.champ_name|eng_to_kor}}</span>
                            </div>
                            <div class="date-type tooltip-div" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-container="body" title="{{r.game_end|unix_to_full_date}}">
                                <span class="date">{{r.game_end|unix_to_date}}</span>
                                <span class="type">{{r.queue_ID|det_game_type}}</span>
                            </div>
                            <div class="result-time">
                                <span class="result">{{r.game_result|det_win_lose}}</span><br>
                                <span class="time">{{r.game_duration|sec_to_min}}분</span>
                            </div>
                            <div class="game-kda">
                                <span class="kill">{{r.kill}}</span>/<!--
                             --><span class="death">{{r.death}}</span>/<!--
                             --><span class="assist">{{r.assist}}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
                <div class="swiper-pagination"></div>
            </div>

    </section>
    </div>
    <!-- game record end-->

    <!-- detail record start-->
    <div class="detail-container mb-3">
        
    </div>
    <!-- detail record end-->

    <!--소환사 정보 End-->

{% else %} <!--소환사 이름이 존재 X(Error)-->
    <!--Error Start-->
    <div class="error-box alert alert-danger align-text-top" role="alert">
        <h1>소환사 '{{ userName }}'에 대한 정보가 존재하지 않습니다!</h1>
    </div>
    <div class="error-img">
        <img class="rounded mx-auto d-block" src="{% static 'images/not_found.png' %}" alt="not_found">
    </div>

    <div class="empty"></div>
    
    <!--Error End-->
{% endif %}
</div>
{%endblock%}

{% block script %}
<!-- Swiper JS -->
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<!-- Initialize Swiper -->
<script>
    var swiper = new Swiper(".mySwiper", {
        slidesPerView: 4,
        spaceBetween: 30,
        slidesPerGroup: 4,
        loop: true,
        loopFillGroupWithBlank: true,
        pagination: {
        el: ".swiper-pagination",
        clickable: true,
        },
        navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
        },
    });
    </script>

<script type="text/javascript">
    STATIC_URL = '{{STATIC_URL}}';
</script>
<script type="text/javascript" src="{% static 'js/summoner.js' %}"></script>
<script type="text/javascript" src="{% static 'js/renew.js' %}"></script>
<script type="text/javascript" src="{% static 'js/record.js' %}"></script>
{% endblock script %}